version: '3.8'

services:
  gateway:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gateway/traefik.yml:/etc/traefik/traefik.yml

  market-data:
    build: ./services/market-data
    environment:
      - FMP_API_KEY=${FMP_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.market.rule=PathPrefix(`/api/market`)"
      - "traefik.http.services.market.loadbalancer.server.port=80"
    depends_on:
      - redis

  company-info:
    build: ./services/company-info
    environment:
      - FMP_API_KEY=${FMP_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.company.rule=PathPrefix(`/api/company`)"
      - "traefik.http.services.company.loadbalancer.server.port=80"

  financial-statements:
    build: ./services/financial-statements
    environment:
      - FMP_API_KEY=${FMP_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financial.rule=PathPrefix(`/api/financial`)"
      - "traefik.http.services.financial.loadbalancer.server.port=80"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 